# Generated by Django 5.1.3 on 2024-12-28 05:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_picture_latitude_picture_longitude'),
    ]

    operations = [
        migrations.AlterField(
            model_name='picture',
            name='latitude',
            field=models.DecimalField(blank=True, decimal_places=20, max_digits=100, null=True),
        ),
        migrations.AlterField(
            model_name='picture',
            name='longitude',
            field=models.DecimalField(blank=True, decimal_places=20, max_digits=100, null=True),
        ),
    ]
